services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: codexos-postgres
    environment:
      POSTGRES_USER: codexos
      POSTGRES_PASSWORD: codexos_secure_password
      POSTGRES_DB: codexos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U codexos"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and websockets
  redis:
    image: redis:7-alpine
    container_name: codexos-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ChromaDB for vector storage
  chromadb:
    image: chromadb/chroma:latest
    container_name: codexos-chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      CHROMA_SERVER_AUTH_PROVIDER: "chromadb.auth.token_authn.TokenAuthenticationServerProvider"
      CHROMA_SERVER_AUTH_CREDENTIALS: "test-token"

  # FastAPI Backend
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: codexos-backend
    environment:
      DATABASE_URL: postgresql+asyncpg://codexos:codexos_secure_password@postgres:5432/codexos_db
      REDIS_URL: redis://redis:6379/0
      WS_MESSAGE_QUEUE: redis://redis:6379/1
      CHROMA_HOST: chromadb
      CHROMA_PORT: 8000
      SECRET_KEY: your-secret-key-change-in-production
      ENVIRONMENT: development
    ports:
      - "8001:8000"
    volumes:
      - ./apps/backend:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      chromadb:
        condition: service_started
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M

  # Next.js Frontend
  frontend:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: codexos-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8001/api/v1
      NEXT_PUBLIC_WS_URL: ws://localhost:8001/ws
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    command: npm run dev
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3000/api/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M

  # Ollama for local LLM (optional)
  ollama:
    image: ollama/ollama:latest
    container_name: codexos-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  postgres_data:
  redis_data:
  chroma_data:
  ollama_data:
